In [24]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import StandardScaler

In [25]:
df=pd.read_csv('linear regression\standard_scaler_dataset.csv')

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
C:\Users\pavan\AppData\Local\Temp\ipykernel_11316\2931336869.py:1: SyntaxWarning: invalid escape sequence '\s'
  df=pd.read_csv('linear regression\standard_scaler_dataset.csv')


In [26]:
df.head()

Age  Salary  Experience
0   56   32695           3
1   46   78190           7
2   32   35258           6
3   60  117538           8
4   25   69504          27

In [27]:
x=df.drop(columns='Experience')
y=df['Experience']

In [28]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.8,random_state=42)

In [29]:
model=LinearRegression()

In [30]:
model.fit(x_train,y_train)

LinearRegression()

In [31]:
model.score(x_train,y_train)

0.0990103113202554

In [32]:
model.score(x_test,y_test)

-0.2036095301647931

In [33]:
model.coef_

array([8.04057518e-02, 7.63443728e-05])

After using standard scaler

In [34]:
scaler=StandardScaler()

In [35]:
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

In [36]:
model_scaled=LinearRegression()

In [37]:
model_scaled.fit(x_train_scaled,y_train)

LinearRegression()

In [38]:
model_scaled.score(x_train_scaled,y_train)

0.0990103113202554

In [39]:
model_scaled.score(x_test_scaled,y_test)

-0.20360953016479288

In [40]:
model_scaled.coef_

array([1.03341725, 2.47018856])

After using Robust scaler

In [45]:
from sklearn.preprocessing import RobustScaler

In [42]:
model_ro=LinearRegression()

In [46]:
r=RobustScaler()

In [47]:
xtrain_scled_r=r.fit_transform(x_train)
xtest_scled_r=r.transform(x_test)

In [51]:
model_ro.fit(xtrain_scled_r,y_train)
model_ro.predict(xtest_scled_r)

array([14.55968049, 18.81298977, 22.86267844, 18.90384382, 13.15795101,
       20.36388316, 13.98189327, 20.09308967, 12.28840585, 14.47365268,
       19.06271505, 22.75935284, 20.59647491, 20.98431945, 14.66298814,
       14.79123439, 15.5223081 , 20.6217449 , 18.9512811 , 18.77274329,
       21.62479841, 16.74330895, 19.36363431, 19.52534753, 21.80248272,
       13.1034137 , 12.38327165, 16.54121523, 14.96801699, 17.35415682,
       15.1119701 , 15.01053868, 16.34012203, 13.97934011, 13.02764983,
       15.35210412, 18.24476073, 15.71524617, 20.72472921, 13.54168879,
       21.46162377, 15.53030347, 17.38229977, 16.7979311 , 19.5052042 ,
       23.34028742, 20.98708298, 19.45303499, 20.29618366, 22.32538117,
       19.86057355, 21.2725613 , 13.6240672 , 18.02753357, 13.94839039,
       13.18700796, 15.33565699, 17.09162294, 13.45490319, 20.21302384,
       15.33124485, 18.87009536, 20.22565588, 20.55212025, 17.20180513,
       18.81931477, 18.56617337, 18.98281274, 16.58511395, 13.57

In [49]:
model_ro.coef_

array([1.52770929, 3.60629822])

Min max scaling

In [52]:
from sklearn.preprocessing import MinMaxScaler

In [53]:
m=MinMaxScaler()

In [54]:
xta_m=m.fit_transform(x_train)
xte_m=m.transform(x_test)

In [ ]:
model.fit(xta_m,y_train)

array([[0.        , 1.        ],
       [1.        , 0.38282223],
       [0.75609756, 0.41847702],
       [0.51219512, 0.16902495],
       [0.56097561, 0.37637859],
       [0.02439024, 0.89247453],
       [0.7804878 , 0.73533744],
       [0.2195122 , 0.        ],
       [0.36585366, 0.6322217 ],
       [0.46341463, 0.1121193 ],
       [0.2195122 , 0.14656427],
       [0.6097561 , 0.5153683 ],
       [0.48780488, 0.14531938],
       [0.95121951, 0.56024582],
       [0.58536585, 0.41202462],
       [0.82926829, 0.44523346],
       [0.09756098, 0.14939596],
       [0.43902439, 0.41198078],
       [0.95121951, 0.34194238],
       [1.        , 0.98381639]])

In [56]:
model.predict(xte_m)

array([14.55968049, 18.81298977, 22.86267844, 18.90384382, 13.15795101,
       20.36388316, 13.98189327, 20.09308967, 12.28840585, 14.47365268,
       19.06271505, 22.75935284, 20.59647491, 20.98431945, 14.66298814,
       14.79123439, 15.5223081 , 20.6217449 , 18.9512811 , 18.77274329,
       21.62479841, 16.74330895, 19.36363431, 19.52534753, 21.80248272,
       13.1034137 , 12.38327165, 16.54121523, 14.96801699, 17.35415682,
       15.1119701 , 15.01053868, 16.34012203, 13.97934011, 13.02764983,
       15.35210412, 18.24476073, 15.71524617, 20.72472921, 13.54168879,
       21.46162377, 15.53030347, 17.38229977, 16.7979311 , 19.5052042 ,
       23.34028742, 20.98708298, 19.45303499, 20.29618366, 22.32538117,
       19.86057355, 21.2725613 , 13.6240672 , 18.02753357, 13.94839039,
       13.18700796, 15.33565699, 17.09162294, 13.45490319, 20.21302384,
       15.33124485, 18.87009536, 20.22565588, 20.55212025, 17.20180513,
       18.81931477, 18.56617337, 18.98281274, 16.58511395, 13.57

In [57]:
model.coef_

array([3.29663583, 8.70829723])