In [104]:
import numpy as np
import seaborn as sns
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder,OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV

In [105]:
df=pd.read_csv(r'C:\Users\pavan\Desktop\data science\logistic regression\loan_data.csv')

In [106]:
df.head()

person_age person_gender person_education  person_income  person_emp_exp  \
0        22.0        female           Master        71948.0               0   
1        21.0        female      High School        12282.0               0   
2        25.0        female      High School        12438.0               3   
3        23.0        female         Bachelor        79753.0               0   
4        24.0          male           Master        66135.0               1   

  person_home_ownership  loan_amnt loan_intent  loan_int_rate  \
0                  RENT    35000.0    PERSONAL          16.02   
1                   OWN     1000.0   EDUCATION          11.14   
2              MORTGAGE     5500.0     MEDICAL          12.87   
3                  RENT    35000.0     MEDICAL          15.23   
4                  RENT    35000.0     MEDICAL          14.27   

   loan_percent_income  cb_person_cred_hist_length  credit_score  \
0                 0.49                         3.0           561   
1                 0.08                         2.0           504   
2                 0.44                         3.0           635   
3                 0.44                         2.0           675   
4                 0.53                         4.0           586   

  previous_loan_defaults_on_file  loan_status  
0                             No            1  
1                            Yes            0  
2                             No            1  
3                             No            1  
4                             No            1

In [107]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 14 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   person_age                      45000 non-null  float64
 1   person_gender                   45000 non-null  object 
 2   person_education                45000 non-null  object 
 3   person_income                   45000 non-null  float64
 4   person_emp_exp                  45000 non-null  int64  
 5   person_home_ownership           45000 non-null  object 
 6   loan_amnt                       45000 non-null  float64
 7   loan_intent                     45000 non-null  object 
 8   loan_int_rate                   45000 non-null  float64
 9   loan_percent_income             45000 non-null  float64
 10  cb_person_cred_hist_length      45000 non-null  float64
 11  credit_score                    45000 non-null  int64  
 12  previous_loan_defaults_on_file  

In [108]:
cat_col=df.select_dtypes(exclude='number')
num_col=df.select_dtypes(include='number')

In [109]:
encoder=OneHotEncoder(sparse_output=False)

In [110]:
val=encoder.fit_transform(cat_col)
idx=encoder.get_feature_names_out()


In [111]:
cat_enco=pd.DataFrame(val,columns=idx)

In [112]:
new_data=pd.concat([cat_enco,num_col],axis=1)

In [113]:
new_data

person_gender_female  person_gender_male  person_education_Associate  \
0                       1.0                 0.0                         0.0   
1                       1.0                 0.0                         0.0   
2                       1.0                 0.0                         0.0   
3                       1.0                 0.0                         0.0   
4                       0.0                 1.0                         0.0   
...                     ...                 ...                         ...   
44995                   0.0                 1.0                         1.0   
44996                   1.0                 0.0                         1.0   
44997                   0.0                 1.0                         1.0   
44998                   0.0                 1.0                         0.0   
44999                   0.0                 1.0                         0.0   

       person_education_Bachelor  person_education_Doctorate  \
0                            0.0                         0.0   
1                            0.0                         0.0   
2                            0.0                         0.0   
3                            1.0                         0.0   
4                            0.0                         0.0   
...                          ...                         ...   
44995                        0.0                         0.0   
44996                        0.0                         0.0   
44997                        0.0                         0.0   
44998                        1.0                         0.0   
44999                        0.0                         0.0   

       person_education_High School  person_education_Master  \
0                               0.0                      1.0   
1                               1.0                      0.0   
2                               1.0                      0.0   
3                               0.0                      0.0   
4                               0.0                      1.0   
...                             ...                      ...   
44995                           0.0                      0.0   
44996                           0.0                      0.0   
44997                           0.0                      0.0   
44998                           0.0                      0.0   
44999                           1.0                      0.0   

       person_home_ownership_MORTGAGE  person_home_ownership_OTHER  \
0                                 0.0                          0.0   
1                                 0.0                          0.0   
2                                 1.0                          0.0   
3                                 0.0                          0.0   
4                                 0.0                          0.0   
...                               ...                          ...   
44995                             0.0                          0.0   
44996                             0.0                          0.0   
44997                             0.0                          0.0   
44998                             0.0                          0.0   
44999                             0.0                          0.0   

       person_home_ownership_OWN  ...  previous_loan_defaults_on_file_Yes  \
0                            0.0  ...                                 0.0   
1                            1.0  ...                                 1.0   
2                            0.0  ...                                 0.0   
3                            0.0  ...                                 0.0   
4                            0.0  ...                                 0.0   
...                          ...  ...                                 ...   
44995                        0.0  ...                                 0.0   
44996                        0.0  ...                          

In [114]:
x=new_data.drop(columns='loan_status')
y=new_data['loan_status']

In [115]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=42)

In [116]:
grid=GridSearchCV(LogisticRegression(),param_grid={'penalty':['l2'],
                                              'solver':['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga']},cv=3,verbose=2,n_jobs=-1,scoring='f1')

In [117]:
grid.fit(x_train, y_train)

Fitting 3 folds for each of 6 candidates, totalling 18 fits


GridSearchCV(cv=3, estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'penalty': ['l2'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='f1', verbose=2)

In [118]:
grid.best_params_


{'penalty': 'l2', 'solver': 'newton-cholesky'}

In [133]:
model=LogisticRegression(penalty='l2',solver='newton-cholesky')

In [134]:
model.fit(x_train,y_train)

LogisticRegression(solver='newton-cholesky')

In [135]:
model.score(x_train,y_train)

0.8970555555555556

In [136]:
model.predict(x_test)

array([0, 0, 1, ..., 1, 1, 1], shape=(9000,))

In [137]:
model.score(x_test,y_test)

0.8934444444444445

In [138]:
new_data.corr()['loan_status']

person_gender_female                  0.000561
person_gender_male                   -0.000561
person_education_Associate           -0.002765
person_education_Bachelor             0.004728
person_education_Doctorate            0.001833
person_education_High School          0.001277
person_education_Master              -0.004741
person_home_ownership_MORTGAGE       -0.213451
person_home_ownership_OTHER           0.013645
person_home_ownership_OWN            -0.093666
person_home_ownership_RENT            0.255239
loan_intent_DEBTCONSOLIDATION         0.084130
loan_intent_EDUCATION                -0.064006
loan_intent_HOMEIMPROVEMENT           0.033838
loan_intent_MEDICAL                   0.065195
loan_intent_PERSONAL                 -0.022488
loan_intent_VENTURE                  -0.085992
previous_loan_defaults_on_file_No     0.543096
previous_loan_defaults_on_file_Yes   -0.543096
person_age                           -0.021476
person_income                        -0.135808
person_emp_ex

In [139]:
model.coef_

array([[-1.23466394e-02,  1.23466394e-02,  2.83462559e-02,
        -9.37450211e-03, -7.45177202e-02,  3.39279205e-02,
         2.16180459e-02,  6.02720244e-02,  4.33999329e-01,
        -1.30882091e+00,  8.14549560e-01,  4.92464584e-01,
        -3.38132514e-01,  4.71397946e-01,  2.38865628e-01,
        -1.83938163e-01, -6.80657481e-01,  4.17742024e+00,
        -4.17742024e+00,  2.29452910e-02,  8.40378009e-08,
        -1.92822499e-02, -8.47802424e-05,  3.25835493e-01,
         1.42619631e+01, -4.53098522e-03, -8.72714846e-03]])

In [126]:
model.intercept_

array([-0.00143452])

In [127]:
model1=LogisticRegression(max_iter=1000,penalty='l1',solver='liblinear') 

In [128]:
model1.fit(x_train,y_train)

LogisticRegression(max_iter=1000, penalty='l1', solver='liblinear')

In [129]:
model1.predict(x_test)

array([0, 0, 1, ..., 0, 1, 1], shape=(9000,))

In [130]:
model1.intercept_

array([-0.71020778])

In [131]:
model.coef_ # penalt with none

array([[-2.82998904e-04, -1.15151519e-03, -5.95174623e-04,
         1.22537177e-04,  8.05347117e-05, -1.38119236e-03,
         3.38781001e-04, -2.90897698e-02,  2.62331277e-04,
        -1.53669669e-02,  4.27598913e-02,  1.54296559e-02,
        -1.30683396e-02,  7.72658287e-03,  9.27476009e-03,
        -4.07988067e-03, -1.67172927e-02,  1.20381745e-01,
        -1.21816259e-01, -3.19402702e-02, -2.87600563e-05,
        -3.21765634e-03,  9.03121101e-05,  3.07577101e-01,
         3.75285024e-03, -3.34733667e-03, -4.47045451e-03]])

In [132]:
model1.coef_ # penalty without none

array([[-5.19015722e-01, -4.91388298e-01,  2.63169551e-02,
        -1.79922635e-02, -8.75901275e-02,  4.15257047e-02,
         0.00000000e+00, -4.87699622e-01,  0.00000000e+00,
        -1.98102321e+00,  2.20695537e-01,  2.71313120e-01,
        -5.80130192e-01,  2.61359288e-01,  5.24172407e-03,
        -4.21505475e-01, -9.37019060e-01,  7.73787984e-01,
        -9.03231520e+00,  3.32084761e-03,  5.51216307e-07,
        -7.67850284e-03, -9.93083317e-05,  3.33283863e-01,
         1.57849668e+01,  5.25440768e-03, -7.71723644e-03]])