In [47]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

# LABEL ENCODER

In [48]:
df=pd.DataFrame({'Color':['Red','Blue','Green','Red','Yellow']})

In [49]:
df

Color
0     Red
1    Blue
2   Green
3     Red
4  Yellow

In [50]:
label=LabelEncoder()

In [51]:
label.fit_transform(df['Color'])

array([2, 0, 1, 2, 3])

In [53]:
label.transform(['Red']) #[2]
label.transform(['Black']) # ValueError 
label.transform([['yes','no']]) #y should be 1D array


ValueError: y contains previously unseen labels: 'Black'

# ONEHOT ENCODER

In [54]:
df1=pd.DataFrame({'Color':['Red','Blue','Green','Red','Yellow'],'City':['Bengaluru','chennai','hydrabad','Bengaluru','hydrabad']})
df1

Color       City
0     Red  Bengaluru
1    Blue    chennai
2   Green   hydrabad
3     Red  Bengaluru
4  Yellow   hydrabad

In [ ]:
one_label=OneHotEncoder(handle_unknown='ignore') #sparse_output=False  ---> directly we get the values instead of sparse matrix
                          # dtype='int' --> used convert the values to int default its float

In [69]:
nes=one_label.fit_transform(df1[['Color','City']]) #returns sparse matrix 

In [57]:
val=nes.toarray() # to extract that values...from the sparse matrix
val

array([[0., 0., 1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 1.]])

In [58]:
res=one_label.get_feature_names_out() # array of labels or categorical values 
res

array(['Color_Blue', 'Color_Green', 'Color_Red', 'Color_Yellow',
       'City_Bengaluru', 'City_chennai', 'City_hydrabad'], dtype=object)

In [59]:
pd.DataFrame(val,columns=res)

Color_Blue  Color_Green  Color_Red  Color_Yellow  City_Bengaluru  \
0         0.0          0.0        1.0           0.0             1.0   
1         1.0          0.0        0.0           0.0             0.0   
2         0.0          1.0        0.0           0.0             0.0   
3         0.0          0.0        1.0           0.0             1.0   
4         0.0          0.0        0.0           1.0             0.0   

   City_chennai  City_hydrabad  
0           0.0            0.0  
1           1.0            0.0  
2           0.0            1.0  
3           0.0            0.0  
4           0.0            1.0

In [ ]:
mat=one_label.transform([['Blue','Bengaluru']])

c:\Users\pavan\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [ ]:
val=mat.toarray()
val

array([[1., 0., 0., 0., 1., 0., 0.]])

In [ ]:
#mat=one_label.transform([['Bluee','Bengaluru']])  

# #ValueError: Found unknown categories ['Bluee'] in column 0 during transform

In [ ]:
one_label.transform()

c:\Users\pavan\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 0., 0., 0., 0., 0.]])